In [1]:
import pandas as pd
import numpy as np

In [2]:
customer = pd.read_csv("../../data/Telco_Cusomer_Churn.csv")

In [3]:
customer.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [4]:
customer.shape

(7043, 21)

In [5]:
customer.info()

<class 'pandas.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   str
 1   gender            7043 non-null   str
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   str
 4   Dependents        7043 non-null   str
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   str
 7   MultipleLines     7043 non-null   str
 8   InternetService   7043 non-null   str
 9   OnlineSecurity    7043 non-null   str
 10  OnlineBackup      7043 non-null   str
 11  DeviceProtection  7043 non-null   str
 12  TechSupport       7043 non-null   str
 13  StreamingTV       7043 non-null   str
 14  StreamingMovies   7043 non-null   str
 15  Contract          7043 non-null   str
 16  PaperlessBilling  7043 non-null   str
 17  PaymentMethod     7043 non-null   str
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7043 non-null   str
 20  Churn             7043 non-null   str
dtypes: float64(1), int64(2), str(18)
memory usage: 1.1 MB

In [6]:
customer.columns

Index(['customerID', 'gender', 'SeniorCitizen', 'Partner', 'Dependents',
       'tenure', 'PhoneService', 'MultipleLines', 'InternetService',
       'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport',
       'StreamingTV', 'StreamingMovies', 'Contract', 'PaperlessBilling',
       'PaymentMethod', 'MonthlyCharges', 'TotalCharges', 'Churn'],
      dtype='str')

In [7]:
numerice = pd.to_numeric(customer["TotalCharges"], errors="coerce")

In [8]:
customer.loc[numerice.isna(),"TotalCharges"]

488
753
936
1082
1340
3331
3826
4380
5218
6670
6754
Name: TotalCharges, dtype: str

In [9]:
l=[488,      
753,      
936,      
1082,     
1340 ,    
3331,     
3826,     
4380,     
5218,     
6670,     
6754 ]
for i in l:
    print(f'{i} = {customer.loc[i,"TotalCharges"]}')

488 =
753 =
936 =
1082 =
1340 =
3331 =
3826 =
4380 =
5218 =
6670 =
6754 =

In [10]:
customer["TotalCharges"] = pd.to_numeric(customer["TotalCharges"], errors="coerce")

In [11]:
customer["TotalCharges"].dtypes

dtype('float64')

In [14]:
customer.describe(include="all").T

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
customerID,7043,7043,7590-VHVEG,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
gender,7043,2,Male,3555,NaN,NaN,NaN,NaN,NaN,NaN,NaN
SeniorCitizen,7043.0,NaN,NaN,NaN,0.162147,0.368612,0.0,0.0,0.0,0.0,1.0
Partner,7043,2,No,3641,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Dependents,7043,2,No,4933,NaN,NaN,NaN,NaN,NaN,NaN,NaN
tenure,7043.0,NaN,NaN,NaN,32.371149,24.559481,0.0,9.0,29.0,55.0,72.0
PhoneService,7043,2,Yes,6361,NaN,NaN,NaN,NaN,NaN,NaN,NaN
MultipleLines,7043,3,No,3390,NaN,NaN,NaN,NaN,NaN,NaN,NaN
InternetService,7043,3,Fiber optic,3096,NaN,NaN,NaN,NaN,NaN,NaN,NaN
OnlineSecurity,7043,3,No,3498,NaN,NaN,NaN,NaN,NaN,NaN,NaN
OnlineBackup,7043,3,No,3088,NaN,NaN,NaN,NaN,NaN,NaN,NaN
DeviceProtection,7043,3,No,3095,NaN,NaN,NaN,NaN,NaN,NaN,NaN
TechSupport,7043,3,No,3473,NaN,NaN,NaN,NaN,NaN,NaN,NaN
StreamingTV,7043,3,No,2810,NaN,NaN,NaN,NaN,NaN,NaN,NaN
StreamingMovies,7043,3,No,2785,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Contract,7043,3,Month-to-month,3875,NaN,NaN,NaN,NaN,NaN,NaN,NaN
PaperlessBilling,7043,2,Yes,4171,NaN,NaN,NaN,NaN,NaN,NaN,NaN
PaymentMethod,7043,4,Electronic check,2365,NaN,NaN,NaN,NaN,NaN,NaN,NaN
MonthlyCharges,7043.0,NaN,NaN,NaN,64.761692,30.090047,18.25,35.5,70.35,89.85,118.75
TotalCharges,7032.0,NaN,NaN,NaN,2283.300441,2266.771362,18.8,401.45,1397.475,3794.7375,8684.8
Churn,7043,2,No,5174,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [19]:
missing_count = customer.isnull().sum()
missing_summary = pd.DataFrame({
    "missing_count": missing_count,
    "missing_percentage":(
        customer.isnull().mean()*100
    ).round(2)
})
missing_summary = missing_summary.sort_values(
    "missing_percentage",
    ascending=False
)
missing_summary

                  missing_count  missing_percentage
TotalCharges                 11                0.16
gender                        0                0.00
SeniorCitizen                 0                0.00
Partner                       0                0.00
customerID                    0                0.00
Dependents                    0                0.00
tenure                        0                0.00
MultipleLines                 0                0.00
PhoneService                  0                0.00
OnlineSecurity                0                0.00
OnlineBackup                  0                0.00
DeviceProtection              0                0.00
InternetService               0                0.00
TechSupport                   0                0.00
StreamingTV                   0                0.00
Contract                      0                0.00
StreamingMovies               0                0.00
PaperlessBilling              0                0.00
PaymentMethod                 0                0.00
MonthlyCharges                0                0.00
Churn                         0                0.00

In [21]:
print("Duplicated rows : ",customer.duplicated().sum())

Duplicated rows :  0

In [29]:
summary = {
    "rows": customer.shape[0],
    "columns": customer.shape[1],
    "duplicated_rows": customer.duplicated().sum(),
    "columns_with_missing_values":customer.isnull().any().sum(),
    "total_missing_values": customer.isnull().sum().sum(),
    "duplicate_columns_name":customer.columns.duplicated().sum()
}
pd.Series(summary,name='value')

rows                           7043
columns                          21
duplicated_rows                   0
columns_with_missing_values       1
total_missing_values             11
duplicate_columns_name            0
Name: value, dtype: int64